config:

  #Set Language for the plugin
  # Available languages: en_En - es_Es - fr_Fr
  Lang: "en_En"

  #Welcome message true/false
  Message-Welcome: true

  #Leave message true/false
  Leave-message: true

  #Join message true/false
  Join-message: true

  #Join message for all true/false
  Join-messageall: true

  #Join Particle true/false
  Join-particle: true

  #First Join message true/false
  First-join: true

  #Join Sound true/false
  Join-Sound: true

  #Death message true/false
  Death: true

  #Join particle
  Join-particle-select: FLAME

  #Join sound
  Join-sound-select: ENTITY_WITHER_SPAWN


  #Join Commanns <-add commands>
  Join-Commands:
    - ""

  #Join particle tick speed
  Particle-ticks: 21

  #"You can set the timeout in ticks for particles."#
  #"You can set colors with the & sign and assign numeric value colors"#
  #"join in this link for more: https://minecraft.tools/en/color-code.php"#
  #"The %player% identific the player name"#
  #"Use the command /welcomer reload to reload"*\#"



