name: Welcomer_Plus
version: 2.5.5
main: com.gmail.arieldeleonhernandez123.welcomer_plus.Welcomer_Plus
api-version: 1.15
authors: [ Elcheems, Divios ]
commands:
 welcomer:
   description: multiples opciones
   permission: Screen_Welcomer.welcomer
   default: not op
   permission-message: you don´t have permission <permission>

permissions:
  Screen_Welcomer.joincomands:
    description: permisos para el comando join

  Screen_Welcomer.allmesage:
    description: none
    permission-message: You don't have <permission>
