name: Welcomer_Plus
version: 2.2.0
main: com.gmail.arieldeleonhernandez123.welcomer_plus.Welcomer_Plus
api-version: 1.15
authors: [ Elcheems, Divios ]
commands:
 welcomer:
   description: multiples opciones
   permission: Screen_Welcomer.welcomer
   usage: /welcomer
   permission-message: you don´t have permission= <permission>
 mesageall:
  permission: Screen_Welcomer.allmesage
 comandper:
   permission: Screen_Welcomer.joincomands
